### ISSUE TITLE
new icon

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-earth#1]
Hey @samanpwbb, any chance you could spare some cycles in the next couple months for a new icon for this app? I've heard from a couple sources that it's confusing because it looks like it's disabled, but also, we need a visual refresh for iOS 7. Something maybe with a satellite and/or globe in the new grid style could be cool. Happy to provide design resources if you want to read up on this. 

![](http://g.foolcdn.com/editorial/images/49315/ios-7-icons_large.png)

**Comment by samanpwbb** [comment]
@ryantroyford this looks like something you can take on. Should be fun.

@incanus can you post links to comprehensive asset guidelines for Ryan?

**Comment by yhahn** [comment]
you too can contribute to the wonder that is ios7

**Comment by yhahn** [comment]
- world wonder

**Comment by ryantroyford** [comment]
this looks like fun. i'll start sketching some things out.

note to self: gradients.

**Comment by tmcw** [comment]
Some color inspiration for you:

![](http://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Sufjan_Stevens,_August_2011.jpg/267px-Sufjan_Stevens,_August_2011.jpg)

**Comment by incanus** [comment]
![](http://queensizedflava.com/wp-content/uploads/2011/10/Haters-Gonna-Hate_1.jpg)

**Comment by tristen** [comment]
![](http://24.media.tumblr.com/9be6af176ef07c188435bc165e971a22/tumblr_molo6vvfbf1svn1xeo1_500.jpg)

**Comment by celoyd** [comment]
![images](https://f.cloud.github.com/assets/148985/822093/15a67008-efe8-11e2-90fe-8c54cda24737.jpeg)

**Comment by incanus** [comment]
@ryantroyford I'll still get you some reading on this, but Apple's dev portal has been under maintenance since yesterday in some bizarro alternate internet rules universe so I can't yet.

**Comment by incanus** [comment]
Still waiting for Apple to get this back up. Security breach.

**Comment by incanus** [comment]
Apple's still down, but here's some inspiration: http://www.glyphish.com

**Comment by incanus** [comment]
Yay, this is back up now @ryantroyford: 

https://developer.apple.com/library/prerelease/ios/design/index.html

You will need a (free) developer account to access it. Let me know if you have any questions.

**Comment by ryantroyford** [comment]
@incanus used my apple ID, and i'm getting one of these when i log in:

![error](http://i.imgur.com/rTbjUwn.png)

**Comment by incanus** [comment]
Hmm, try again going to the above link. It works for me after being logged in.

**Comment by incanus** [comment]
@ryantroyford, any luck here? If this is still a problem, I can Dropbox a bunch of docs from this.

**Comment by ryantroyford** [comment]
@incanus now i'm getting this. it looks like the dev programs are an [annual fee](https://developer.apple.com/programs/) unless i'm missing it. i feel like i should probably get myself access to [this kind of stuff](https://developer.apple.com/ios7/), though i'm probably just overlooking the place to do that.

![screen shot 2013-08-13 at 10 25 42 am](https://f.cloud.github.com/assets/937626/955097/4cfc3498-0424-11e3-8dbe-5fe14a0920bc.png)

**Comment by incanus** [comment]
Hmm, what email address do you use for the Apple ID? I'll add you to our already-paid-for iOS team and see if that helps.

**Comment by ryantroyford** [comment]
that'd be great. for my Apple ID i'm using ryan@ryantroyford.com

**Comment by incanus** [comment]
Invite sent.

**Comment by ryantroyford** [comment]
it's simple, but it's one of the concepts i had thought of fleshed out in inkscape. thoughts? 

![screen shot 2013-08-13 at 2 36 33 pm](https://f.cloud.github.com/assets/937626/956940/74f228fe-0447-11e3-904f-f997ae4ad845.png)

cc @samanpwbb

**Comment by incanus** [comment]
Oh, badass. It won't have the shadow, but that looks good here for presentation. I like the concept a lot.

**Comment by ryantroyford** [comment]
yeah, just threw the shadow in there to define the icon area.

**Comment by KalofXeno** [comment]
How does it look with an axial tilt of 23.4 degrees?

**Comment by incanus** [comment]
To put a date on this, iOS 7 is rumored to be announced on 9/10, with apps going into submission possibly earlier. We want to get in on that, so we've got maybe two weeks around this.

**Comment by ryantroyford** [comment]
@incanus how are you feeling about the above concept? i can make it on more of a realistic axial tilt as @KalofXeno suggested. i can also take another run at it if you're not stoked about this one.

**Comment by incanus** [comment]
> I like the concept a lot.

Still holds :-)

If you can get me like a 512px, I will try it out real quick in a live app and see what we think.

**Comment by ryantroyford** [comment]
@incanus gaahh totally forgot about that. hah. sorry man. here's a 512x512.

![export-01-512](https://f.cloud.github.com/assets/937626/988583/ce002dc6-0904-11e3-9631-57214a007121.png)

**Comment by incanus** [comment]
I'm pretty happy with this, @ryantroyford -- nice work. I think it looks good in iOS 6 & 7 both, so I'll work on doing a submission for the store. This 512px should be all I need, as I sized it down for the code and will use this size for the iTunes artwork.

**Comment by incanus** [comment]
![screen shot 2013-08-19 at 1 53 28 pm](https://f.cloud.github.com/assets/17722/989312/efb2b5b2-0911-11e3-9859-5f60026d4a27.png)
![screen shot 2013-08-19 at 1 52 45 pm](https://f.cloud.github.com/assets/17722/989313/efd81bf4-0911-11e3-8048-7e8602ab5023.png)
![screen shot 2013-08-19 at 1 52 01 pm](https://f.cloud.github.com/assets/17722/989314/f02317e4-0911-11e3-86e4-158a45dba771.png)

**Comment by gundersen** [comment]
@ryantroyford this is way to literal. What we have now is better. This looks hooky.Where can you even seen a globe any more outside of a museum? in a 3rd grade class room?

Lets try again. Even it it is a light blue circle.

**Comment by ryantroyford** [comment]
@gundersen i'll take another run at it, but i think we need to steer away from a picture of earth. it's an easy solution, but everyone and their brother making a globe app is using it as the icon. 

![screen shot 2013-08-19 at 5 15 44 pm](https://f.cloud.github.com/assets/937626/989467/1166745c-0915-11e3-863b-ff1d27ee1d84.png)

**Comment by tmcw** [comment]
a satellite or a rocket maybe?

**Comment by gundersen** [comment]
eh, I mean it is called "MapBox Earth" I think it is fine to have an Earth on it, I don't think that is where we want to win on the distinction, rather we want it to be conflated w/ Google Earth.

**Comment by ryantroyford** [comment]
@gundersen fair enough. do you just want to keep it pretty much the way it is? i'll address the issues @incanus initially stated here, but i'm fine with keeping the layout more-or-less the same.

**Comment by gundersen** [comment]
Yes. Keep as close to as is. Or as globe. 

-sent from the mobile-

**Comment by incanus** [comment]
What about just a round, non-stylized globe (unlike our logo) with cyan continents, white oceans, black/grey hairline circle border, and white background to the icon?

**Comment by ryantroyford** [comment]
how about something like this? the continental shading is taken directly from our terrain layer. 

![export-02](https://f.cloud.github.com/assets/937626/1026726/e1e00a7e-0e62-11e3-8e83-2891222f13df.png)

**Comment by incanus** [comment]
I'm liking this pretty well. Even naively resized, it looks good in the smaller versions: 

![e1e00a7e-0e62-11e3-8e83-2891222f13df](https://f.cloud.github.com/assets/17722/1027339/69a1f6d2-0e6f-11e3-9748-3d7a8045319f.png)

![small](https://f.cloud.github.com/assets/17722/1027340/6c633cb4-0e6f-11e3-896b-4fd18a452e77.png)

Thinking again, something not the standard green/blue (like MapBox cyan) probably wouldn't be easily recognizable as a globe, so I like this design, @ryantroyford. 

Note that you won't round the corners yourself.

**Comment by incanus** [comment]
Possibly pretty useful @ryantroyford: http://wearemothership.com/work/prepo/

**Comment by incanus** [comment]
Any final items here @ryantroyford or is the one two comments above our baby? If so, can you either post a final, non-rounded version, or else I will just edit the above and 'shop it myself? Then I'll get an update in the queue for next week.

**Comment by incanus** [comment]
Ping @ryantroyford again -- iOS 7 comes out Wednesday and I am hearing that review times currently are about one day, so we can still make this.

**Comment by ryantroyford** [comment]
sorry for slacking a bit on this @incanus. i'm good with this if you are. here's a the final, big as hell. 

![final-export-1](https://f.cloud.github.com/assets/937626/1151076/d12f891e-1ef4-11e3-889e-9bb559039316.png)

**Comment by incanus** [comment]
I'm seeing the globe sized just a tiny bit too small to fit the iOS 7 "grid" guidelines, so it looks odd compared to other icons. Here's an overlay with the grid at two opacities: 

![screen shot 2013-09-16 at 3 19 30 pm](https://f.cloud.github.com/assets/17722/1153299/8a6a28fc-1f1e-11e3-9d37-b7e475782cd1.png)

![screen shot 2013-09-16 at 3 19 34 pm](https://f.cloud.github.com/assets/17722/1153301/8d3230d4-1f1e-11e3-8527-112f4a0497a2.png)

**Comment by ryantroyford** [comment]
ahh, word. should be a relatively easy fix. is the grid template in the developer toolkit somewhere?

**Comment by incanus** [comment]
Well, bizarrely, Apple makes it really hard to find such a thing, so I dug around a bit: 
- http://freebbble.com/2013/06/12/ios-7-grid-system-icon-template/
- http://www.eazytiger.net/blog/the-first-ios-7-icon-grid-photoshop-template
- http://www.titanui.com/18665-new-ios-7-look-icon-design-grid-psd-template/
- http://www.vcarrer.com/2013/06/demystification-of-ios7-icon-grid-design.html

Any of those should do; they look right.

**Comment by ryantroyford** [comment]
thanks for digging those up. i tried to match a little better to the grid - let me know how it looks.

![final-export-2](https://f.cloud.github.com/assets/937626/1158508/979ffbd6-1fb5-11e3-8d48-7bb5e6a7c6d7.png)

**Comment by incanus** [comment]
![](http://cache.ohinternet.com/images/2/2a/Ytmnd-logo.png)
