### ISSUE TITLE
Annotations on globe

### ISSUE THREAD

**Issue by dcacenabes** [mapbox/mapbox-earth#2]
Hi,

Is it possible to add annotations (markers or paths) to the globe? Something similar to the mapbox iOS SDK.

Thanks.

**Comment by incanus** [comment]
Yes, but this is better done with the upstream [WhirlyGlobe project](https://github.com/mousebird/WhirlyGlobe), upon which Mapbox Earth is built. This project is more of an example of that framework + Mapbox maps working together.
